rabbitdetails:
  - username:
      - admin
  - password:
      - P@ssword
  - host:
      - 127.0.0.1
  - topic:
      - secure_interoperable_data_sharing
  - port:
      - 5672
  - exchange:
      - secure_interoperable_data_sharing
  - queuename:
      - secure_interoperable_data_sharing

graphdbdetails:
  - username:
      - admin
  - password:
      - pwd
  - host:
      - https://smashhitactool.sti2.at/repositories
  - repository:
      - sensor_mapper_tek