rabbitdetails:
  - username:
      - admin
  - password:
      - P@ssword
  - host:
      - 138.232.18.143
  - data_publish_topic:
      - secure_interoperable_data_sharing
  - port:
      - 5672
  - data_publish_exchange:
      - secure_interoperable_data_sharing
  - queuename:
      - secure_interoperable_data_sharing
  - result_publish_topic:
      - reasoning_result_secure_interoperable_data_sharing
  - result_publish_exchange:
      - reasoning_result_secure_interoperable_data_sharing

edgeintelligencemode:
  - mode:
      - edge

graphdbdetails:
  - username:
      - admin
  - password:
      - Sm@shHitA_CT00L
  - host:
      - https://smashhitactool.sti2.at/repositories
  - repository:
      - sensor_mapper_tek