rabbitdetails:
  - username:
      - admin
  - password:
      - P@ssword
  - host:
      - 138.232.18.143
  - data_publish_topic:
      - secure_interoperable_data_sharing
  - port:
      - 5672
  - data_publish_exchange:
      - secure_interoperable_data_sharing
  - queuename:
      - secure_interoperable_data_sharing
  - result_publish_topic:
      - reasoning_result_secure_interoperable_data_sharing
  - result_publish_exchange:
      - reasoning_result_secure_interoperable_data_sharing
  - result_queue:
      - reasoning_result_secure_interoperable_data_sharing


edgeintelligencemode:
  - mode:
      - edge

trustability:
  - sensor_manufacturers:
      - Texas Instruments
  - deployed_location:
      - Yishun
  - deployed_by:
      - Texas Instruments
  - url:
      - URL


graphdbdetails:
  - username:
      - USR
  - password:
      - PWD
  - host:
      - URL
  - repository:
      - REPO