rabbitdetails:
  - username:
      - admin
  - password:
      - P@ssword
  - host:
      - 138.232.18.143
  - topic:
      - secure_interoperable_data_sharing
  - port:
      - 5672
  - exchange:
      - secure_interoperable_data_sharing
  - queuename:
      - secure_interoperable_data_sharing

graphdbdetails:
  - username:
      - admin
  - password:
      - password
  - host:
      - https://smashhitactool.sti2.at/repositories
  - repository:
      - sensor_mapper_tek